# This is the server motd.
Server-MOTD:
  Line-1: '                &6&lFonzeMC Survival'
  Line-2: '&a 1.19.4-1.20.2 supported &3| &5Discord.gg/FonzeMC'

# The motd of the player when they join in.
JoinGame-MOTD:
  Enabled: false
  # Check forum for placeholders.
  # Supported for PlaceholderAPI placeholders.
  Messages:
  - '&eWelcome to the server.'

# Server icon.
Custom-Server-Icon:
  # Set to true will load image from motd folder.
  Enabled: false
  # Make sure it's 64 x 64 pixels with png format.
  Image: server-icon.png

# The maximum players of the server.
Server-Maximum-Players:
  Modify: true
  Maximum-Players: 200
